title   EndeavourOS with NVIDIA drivers: Only RTX GPUs, Turing, or later
sort-key  B
linux   /%INSTALL_DIR%/boot/x86_64/vmlinuz-linux-t2
initrd  /%INSTALL_DIR%/boot/x86_64/initramfs-linux-t2.img
options archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% cow_spacesize=10G copytoram=n module_blacklist=pcspkr,nouveau,nouveau_drm nouveau.modeset=0 nvidia_drm.modeset=1 i915.modeset=1 radeon.modeset=1 nvme_load=yes intel_iommu=on iommu=pt pcie_ports=compat
